### Create wallet

POST http://localhost:3000/wallet/create
Content-Type: application/json

{

}

###

### Authenticate
### Enter the username and the keyphrase

POST http://localhost:3000/login
Content-Type: application/json

{
    "keyPhrase": "b3b333f33b075a7754e36447ab52dfc0"
}

### Authorize

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImtleVBocmFzZSI6ImIzYjMzM2YzM2IwNzVhNzc1NGUzNjQ0N2FiNTJkZmMwIn0sImlhdCI6MTY2Mjc3MDAzMn0.mN94nfU1_vpaKMDuUAyEzu_7zaC1AE1pIaZ03oy93bA"
}

### Enter the access token given.

GET http://localhost:3000/wallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXlQaHJhc2UiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlJanA3SW10bGVWQm9jbUZ6WlNJNkltSXpZak16TTJZek0ySXdOelZoTnpjMU5HVXpOalEwTjJGaU5USmtabU13SW4wc0ltbGhkQ0k2TVRZMk1qYzNNREF6TW4wLm1OOTRuZlUxX3ZwYUtNRHVVQXlFenVfN3phQzFBRTFwSWFaMDNveTkzYkEiLCJpYXQiOjE2NjI3NzAwNDIsImV4cCI6MTY2Mjc3MzA0Mn0.U8hqIlSDcqJHQL7acoLyjwNPK4jsgK1trb2x9JgPlig


# {
#     "keyPhrase": "b69389b9745ba922fe65e20cc5667cad"
   
# }
###
