### Create wallet

POST http://localhost:3000/wallet/create
Content-Type: application/json

{

}

###

### Authenticate
### Enter the username and the keyphrase

POST http://localhost:3000/login
Content-Type: application/json

{
    "keyPhrase": "71c9bbb98340fed04ff91f74a7ffe4ac"
}

### Authorize

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXlQaHJhc2UiOiI3MWM5YmJiOTgzNDBmZWQwNGZmOTFmNzRhN2ZmZTRhYyIsImlhdCI6MTY3NjExOTM0NiwiZXhwIjoxNjc2MTIyMzQ2fQ.LmO0OhjpNeqRt__QspLC4p34nBKVtUXYrub7xv__dPk"
}

### Enter the access token given.

GET http://localhost:3000/wallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXlQaHJhc2UiOiI3MWM5YmJiOTgzNDBmZWQwNGZmOTFmNzRhN2ZmZTRhYyIsImlhdCI6MTY3NjExOTM3NCwiZXhwIjoxNjc2MTIyMzc0fQ.PV1Qf7sY7-dYINxzbP9Oi9FNZcWGI85C2C94zN-TfWU


# {
#     "keyPhrase": "b69389b9745ba922fe65e20cc5667cad"
   
# }
###


POST http://localhost:3000/test/text
Content-Type: application/json
{
    "username": "Navid"
}
